// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxidbvwpnzheuvmauhqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4aWRidndwbnpoZXV2bWF1aHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Nzk0MzksImV4cCI6MjA2NjM1NTQzOX0.E6TK6QtwH38VtJREsBWVmP_pO1hbAdEmFxgRgEhO7uU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);